server:
  build: .
  ports:
   - "8080:80"
   - "5858:5858"
  links:
   - db
  environment:
   - DEBUG=true
  volumes:
   - .:/dist

db:
  image: mongo:latest
  ports:
  - "27017:27017"

import:
  image: pbrumblay/cookbook-import:latest
  links:
   - db