server:
  build: .
  ports:
   - "8080:80"
   - "5858:5858"
  links:
   - db
  environment:
   - DEBUG=true
   - APP_CLIENT_ID=538908077140-932r8111cah6ipsld1ojsb4uvc55hfv2.apps.googleusercontent.com
  volumes:
   - .:/dist

db:
  image: mongo:latest
  ports:
  - "27017:27017"

import:
  image: pbrumblay/cookbook-import:latest
  links:
   - db
