web:
  build: web
  ports:
   - "8000:80"
  links:
   - app

app:
  build: app
  ports:
   - "9000:8080"
  links:
   - db

import:
  build: import
  links:
   - db

db:
  image: mongo:latest
  ports:
  - "27017:27017"
